import type { Metadata } from 'next'
import { ConfigProvider } from 'antd';
import StyledComponentsRegistry from '@/lib/Antd/AntdRegistery';
import { theme } from "@/lib/Antd/Config"
import '../globals.scss'
import Layout_C from '@/components/Auth/Layout'


export const metadata: Metadata = {
    title: 'Blaxcorp',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <StyledComponentsRegistry>
                    <ConfigProvider theme={theme}>
                        <Layout_C>
                            {children}
                        </Layout_C>
                    </ConfigProvider>
                </StyledComponentsRegistry>
            </body>
        </html>
    )
}
