import type { Metadata } from 'next'
import StyledComponentsRegistry from '../lib/Antd/AntdRegistery';
import { theme } from "./../lib/Antd/Config"
import './globals.scss'
import { ConfigProvider } from 'antd';

export const metadata: Metadata = {
  title: 'Blaxcorp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <ConfigProvider theme={theme}>
            {children}
          </ConfigProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
